=== hybridmachine/branchcovegarden.com/Schemas/branchcovegarden.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Studio 2018 (https://www.liquid-technologies.com) -->
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="garden_data">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" name="title" type="xs:string" />
        <xs:element minOccurs="0" name="contact">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="name" type="xs:string" />
              <xs:element minOccurs="0" name="address">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="street" type="xs:string" />
                    <xs:element minOccurs="0" name="city" type="xs:string" />
                    <xs:element minOccurs="0" name="state" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
              <xs:element minOccurs="0" name="phone" type="xs:string" />
              <xs:element minOccurs="0" name="email" type="xs:string" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="analytics" type="xs:string" />
        <xs:element minOccurs="0" name="about" type="xs:string" />
        <xs:element minOccurs="0" name="snapshots">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="snapshot">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="image" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="name" type="xs:string" />
        <xs:element minOccurs="0" name="headlines">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="headline">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="title" type="xs:string" />
                    <xs:element minOccurs="0" name="paragraph" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="articles">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" name="article">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="date" type="xs:string" />
                    <xs:element minOccurs="0" name="author" type="xs:string" />
                    <xs:element minOccurs="0" name="title" type="xs:string" />
                    <xs:element minOccurs="0" name="paragraphs">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" name="paragraph" type="xs:string" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="maps">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="map">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="image" type="xs:string" />
                    <xs:element minOccurs="0" name="name" type="xs:string" />
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element minOccurs="0" name="plantings">
          <xs:complexType>
            <xs:sequence>
              <xs:element minOccurs="0" maxOccurs="unbounded" name="planting">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element minOccurs="0" name="name" type="xs:string" />
                    <xs:element minOccurs="0" name="link" type="xs:string" />
                    <xs:element minOccurs="0" name="image" type="xs:string" />
                    <xs:element minOccurs="0" name="type" type="xs:string" />
                    <xs:element minOccurs="0" name="note" type="xs:string" />
                    <xs:element minOccurs="0" name="location" type="xs:string" />
                    <xs:element minOccurs="0" name="schedule">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element minOccurs="0" maxOccurs="unbounded" name="seedstart">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="type" type="xs:string" use="optional" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element minOccurs="0" name="directsow">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="type" type="xs:string" use="optional" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element minOccurs="0" name="transplant">
                            <xs:complexType>
                              <xs:simpleContent>
                                <xs:extension base="xs:string">
                                  <xs:attribute name="type" type="xs:string" use="optional" />
                                </xs:extension>
                              </xs:simpleContent>
                            </xs:complexType>
                          </xs:element>
                          <xs:element minOccurs="0" name="harvest" />
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element minOccurs="0" name="log">
                      <xs:complexType mixed="true">
                        <xs:sequence minOccurs="0">
                          <xs:element minOccurs="0" maxOccurs="unbounded" name="entry">
                            <xs:complexType>
                              <xs:sequence>
                                <xs:element minOccurs="0" name="date" type="xs:string" />
                                <xs:element minOccurs="0" name="image" type="xs:string" />
                                <xs:element minOccurs="0" name="note" type="xs:string" />
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== hybridmachine/branchcovegarden.com/xml_data/branchcovegarden.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Created with Liquid Studio 2018 (https://www.liquid-technologies.com) -->
<garden_data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://www.branchcovegarden.com/xml_schemas/branchcovegarden.xsd">
    <title>The Garden in the Cove</title>
    <contact>
        <name>Brian and Michelle</name>
        <address>
            <street>Waterway Cove</street>
            <city>Austin</city>
            <state>TX</state>
        </address>
        <phone>512.825.0482</phone>
        <email>brian.tabone@gmail.com</email>
    </contact>
    <analytics>UA-29197318-2</analytics>
    <about>
        The goings on in our garden and workshop here in the cove. A quiet garden nook tucked in a corner surrounded by trees and wildlife near our community park.
    </about>
    <snapshots>
        <!-- These are images to display as a backdrop, highlighting events through the year. The name of the images only here, the full path is handled in the template-->
        <snapshot>
            <image>hot_biscuits.jpg</image>
        </snapshot>
        <snapshot>
            <image>gazanias.jpg</image>
        </snapshot>
        <snapshot>
            <image>rosella.jpg</image>
        </snapshot>
        <snapshot>
            <image>sunflower1.jpg</image>
        </snapshot>
    </snapshots>
    <name>Branch Cove Garden</name>
    <headlines>
        <headline>
            <title>
                Seed Starting
            </title>
            <paragraph>
                January marks the start of seed starting for the spring garden.
            </paragraph>
        </headline>
        <headline>
            <title>
                Fall Bulbs
            </title>
            <paragraph>
                Tulips, Hyacinths, and Daffodils for Spring.
            </paragraph>
        </headline>
    </headlines>
    <articles>
        <article>
            <date>Dec-23-2018</date>
            <author>Brian</author>
            <title>Go Live!</title>
            <paragraphs>
                <paragraph>
                    This is our new website, going live for the 2019 season.
                </paragraph>
            </paragraphs>
        </article>
    </articles>
    <maps>
        <map>
            <image>michelle_flower_box_layout1.jpg</image>
            <name>Michelle's Flower Box</name>
        </map>
        <map>
            <image>brian_flower_box.jpg</image>
            <name>Brian's Flower Box</name>
        </map>
    </maps>
    <plantings>
        <planting>
            <name>Spellbound Dark Purple Petunia</name>
            <!-- Vendor information link -->
            <link>
                <![CDATA[https://www.burpee.com/flowers/petunias/petunia-spellbound-dark-purple-hybrid-prod500452.html]]>
            </link>
            <!-- Vendor image link -->
            <image>
                <![CDATA[https://www.burpee.com/dw/image/v2/ABAQ_PRD/on/demandware.static/-/Sites-masterCatalog_Burpee/default/dwa327201d/Images/Product%20Images/prod500452/prod500452.jpg?sw=322&sh=380&sm=fit]]>
            </image>
            <type>Flower</type>
            <note></note>
            <location></location>
            <schedule>
                <seedstart type="planned">01/05/2019</seedstart>
                <seedstart type="actual">01/09/2019</seedstart>
                <transplant type="planned">03/15/2019</transplant>
                <harvest></harvest>
            </schedule>
            <log>
                <entry>
                    <date>02/06/2019</date>
                    <image>petunias_20190206.jpg</image>
                    <note>Seedlings need to move to bigger pots</note>
                </entry>
                <entry>
                    <date>01/09/2019</date>
                    <image></image>
                    <note>Planted in D1 - F2 of seed starter, running on heating mat</note>
                </entry>
                <entry>
                    <date>01/17/2019</date>
                    <image>PetuniaSeedlings2019.jpg</image>
                    <note>Seedlings have sprouted. Note these are both types of Spellbound (half dark purple, half red)</note>
                </entry>
                <entry>
                    <date>02/02/2019</date>
                    <image>petunias_20190202.jpg</image>
                    <note>Seedlings are growing nicely, time to move to individual packs and prune out to single plant per cell</note>
                </entry>
                <entry>
                    <date>03/06/2019</date>
                    <image>petunias_20190306.jpg</image>
                    <note>Interesting comparison in the size of petunias. The batch on the left went into larger pots about 1 week before the lot on the right. Both lots were started at the same time. The moral of the story, seedlings need to be placed in larger pots on schedule to facilitate proper growth.</note>
                </entry>
            </log>
        </planting>
        <planting>
            <name>Spellbound Wine Red Petunia</name>
            <!-- Vendor information link -->
            <link>
                <![CDATA[https://www.burpee.com/flowers/petunias/petunia-spellbound-wine-red-hybrid-prod500455.html]]>
            </link>
            <!-- Vendor image link -->
            <image>
                <![CDATA[https://www.burpee.com/dw/image/v2/ABAQ_PRD/on/demandware.static/-/Sites-masterCatalog_Burpee/default/dw715b528c/Images/Product%20Images/prod500455/prod500455.jpg?sw=322&sh=380&sm=fit]]>
            </image>
            <type>Flower</type>
            <note></note>
            <location></location>
            <schedule>
                <seedstart type="planned">01/05/2019</seedstart>
                <seedstart type="actual">01/09/2019</seedstart>
                <transplant type="planned">03/15/2019</transplant>
                <harvest></harvest>
            </schedule>
            <log>
                <entry>
                    <date>01/09/2019</date>
                    <image></image>
                    <note>Planted in A1 - C2 of seed starter, running on heating mat</note>
                </entry>
            </log>
        </planting>
        <planting>
            <name>Mandarin Orange Cosmos</name>
            <!-- Vendor information link -->
            <link>
                <![CDATA[https://www.burpee.com/flowers/cosmos/cosmos-mandarin-orange-prod500425.html]]>
            </link>
            <!-- Vendor image link -->
            <image>
                <![CDATA[https://www.burpee.com/dw/image/v2/ABAQ_PRD/on/demandware.static/-/Sites-masterCatalog_Burpee/default/dwc446bc9c/Images/Product%20Images/prod500425/prod500425.jpg?sw=322&sh=380&sm=fit]]>
            </image>
            <type>Flower</type>
            <note></note>
            <location></location>
            <schedule>
                <seedstart></seedstart>
                <directsow type="planned">03/01/2019</directsow>
                <transplant></transplant>
                <harvest></harvest>
            </schedule>
        </planting>
        <planting>
            <name>Heirloom Black Hybrid Tomato</name>
            <!-- Vendor information link -->
            <link>
                <![CDATA[https://www.seedsnsuch.com/product/heirloom-black-hybrid-tomato/]]>
            </link>
            <!-- Vendor image link -->
            <image>
                <![CDATA[https://seedsnsuch-qb2qm0z.netdna-ssl.com/wp-content/uploads/2018/11/heirloom-black-hybrid.jpg]]>
            </image>
            <type>Vegetable</type>
            <note></note>
            <location></location>
            <schedule>
                <seedstart type="planned">02/01/2019</seedstart>
                <transplant></transplant>
                <harvest></harvest>
            </schedule>
            <log>
                <entry>
                    <date>01/27/2019</date>
                    <image></image>
                    <note>Planted in positions C3 and C4 in seed starter</note>
                </entry>
            </log>
        </planting>
        <planting>
            <name>Chef’s Choice Red Hybrid Tomato VFF</name>
            <!-- Vendor information link -->
            <link>
                <![CDATA[https://www.seedsnsuch.com/product/chefs-choice-red-hybrid-tomato-vff/]]>
            </link>
            <!-- Vendor image link -->
            <image>
                <![CDATA[https://seedsnsuch-qb2qm0z.netdna-ssl.com/wp-content/uploads/2018/11/chefs-choice-red-hybrid.jpg"]]>
            </image>
            <type>Vegetable</type>
            <note></note>
            <location></location>
            <schedule>
                <seedstart></seedstart>
                <transplant></transplant>
                <harvest></harvest>
            </schedule>
            <log>
                <entry>
                    <date>01/27/2019</date>
                    <image></image>
                    <note>Planted in positions B4 - C2 in seed starter</note>
                </entry>
            </log>
        </planting>
        <planting>
            <name>Charger Hybrid Tomato VFFFAStTylcv</name>
            <!-- Vendor information link -->
            <link>
                <![CDATA[https://www.seedsnsuch.com/product/charger-vfffasttylcv-hybrid/]]>
            </link>
            <!-- Vendor image link -->
            <image>
                <![CDATA[https://seedsnsuch-qb2qm0z.netdna-ssl.com/wp-content/uploads/2018/11/charger-1.jpg]]>
            </image>
            <type>Vegetable</type>
            <note></note>
            <location></location>
            <schedule>
                <seedstart></seedstart>
                <transplant></transplant>
                <harvest></harvest>
            </schedule>
            <log>
                <entry>
                    <date>01/27/2019</date>
                    <image></image>
